import type { CardDef } from "../types";

export const CARDS: Record<string, CardDef> = {
  moss_sleep: {
    id: "moss_sleep",
    name: "苔眠团兽",
    nameEn: "Moss-Sleep Cluster",
    type: "eidolon",
    sources: ["verdant"],
    cost: 1,
    rarity: "common",
    hp: 70,
    skill: { name: "苔扑", cost: 1, text: "造成 20 点伤害。", strike: { damage: 20 } },
    text: "一团沉睡的活苔。",
    artHue: 128,
    artKind: "moss",
  },
  moss_crown: {
    id: "moss_crown",
    name: "苔冠守兽",
    nameEn: "Moss-Crown Warden",
    type: "eidolon",
    sources: ["verdant"],
    cost: 1,
    rarity: "rare",
    hp: 110,
    resonanceFrom: "moss_sleep",
    resonanceCost: 1,
    resonanceText: "共鸣时治疗自身 20 点。本场累计治疗需达到 30 点。",
    skill: {
      name: "苔冠守望",
      cost: 2,
      text: "造成 30 点伤害，然后治疗一名友方幻兽 10 点。",
      strike: { damage: 30 },
      follow: [{ kind: "healTarget", amount: 10 }],
    },
    text: "苔眠团兽的共鸣形态。",
    artHue: 140,
    artKind: "moss",
  },
  vine_weasel: {
    id: "vine_weasel",
    name: "藤灯鼬",
    nameEn: "Lantern Weasel",
    type: "eidolon",
    sources: ["verdant"],
    cost: 1,
    rarity: "rare",
    hp: 60,
    skill: {
      name: "引灯",
      cost: 1,
      text: "造成 10 点伤害。查看牌库顶 2 张并重新排列。",
      strike: { damage: 10 },
      follow: [{ kind: "look", count: 2, title: "引灯" }],
    },
    text: "提着藤灯的小兽。",
    artHue: 92,
    artKind: "moss",
  },
  pale_wood: {
    id: "pale_wood",
    name: "苍木守灵",
    nameEn: "Palewood Spirit",
    type: "eidolon",
    sources: ["verdant"],
    cost: 4,
    rarity: "arcane",
    hp: 130,
    skill: {
      name: "林息",
      cost: 3,
      text: "造成 30 点伤害，然后治疗所有友方幻兽各 10 点。",
      strike: { damage: 30 },
      follow: [{ kind: "healAll", amount: 10 }],
    },
    text: "古林凝成的守灵。",
    artHue: 150,
    artKind: "moss",
  },
  microstar: {
    id: "microstar",
    name: "微星虫",
    nameEn: "Microstar Mothling",
    type: "eidolon",
    sources: ["astral"],
    cost: 1,
    rarity: "common",
    hp: 50,
    skill: {
      name: "微芒",
      cost: 1,
      text: "造成 10 点伤害。查看牌库顶 2 张并重新排列。",
      strike: { damage: 10 },
      follow: [{ kind: "look", count: 2, title: "微芒" }],
    },
    text: "星图上的一粒活光。",
    artHue: 220,
    artKind: "star",
  },
  weave_moth: {
    id: "weave_moth",
    name: "织星蛾",
    nameEn: "Starweave Moth",
    type: "eidolon",
    sources: ["astral"],
    cost: 1,
    rarity: "rare",
    hp: 90,
    resonanceFrom: "microstar",
    resonanceCost: 1,
    resonanceText: "本场累计观视牌顶至少 6 张。",
    skill: {
      name: "星织",
      cost: 2,
      text: "造成 30 点伤害。查看牌库顶 3 张并重新排列。",
      strike: { damage: 30 },
      follow: [{ kind: "look", count: 3, title: "星织" }],
    },
    text: "微星虫的共鸣形态。",
    artHue: 235,
    artKind: "star",
  },
  star_owl: {
    id: "star_owl",
    name: "星眸鸮",
    nameEn: "Star-Eyed Owl",
    type: "eidolon",
    sources: ["astral"],
    cost: 2,
    rarity: "rare",
    hp: 80,
    skill: {
      name: "双星凝视",
      cost: 1,
      text: "造成 20 点伤害。查看对方牌库顶 1 张，可留在顶或置于底。",
      strike: { damage: 20 },
      follow: [{ kind: "opponentTop" }],
    },
    text: "凝视夜的下一页。",
    artHue: 250,
    artKind: "star",
  },
  star_fox: {
    id: "star_fox",
    name: "星灯狐",
    nameEn: "Star-Lamp Fox",
    type: "eidolon",
    sources: ["astral", "verdant"],
    cost: 3,
    rarity: "arcane",
    hp: 90,
    skill: {
      name: "寻星",
      cost: 2,
      text: "对敌方主契造成 20 点伤害。查看你牌库顶 3 张牌，选择其中 1 张森源或星源牌置于牌库顶，并调整其余牌的顺序。",
      strike: { damage: 20 },
      follow: [{ kind: "foxLook" }],
    },
    text: "微光引路：每回合第一次从牌库检索入手时，治疗主契幻兽 10 点。",
    artHue: 200,
    artKind: "star",
  },
  mist_path: {
    id: "mist_path",
    name: "雾径",
    nameEn: "Mist Path",
    type: "spell",
    sources: ["astral"],
    cost: 1,
    rarity: "common",
    text: "免费换位。若新主契为星源，查看牌库顶 1 张。",
    artHue: 200,
    artKind: "spell",
  },
  sprout: {
    id: "sprout",
    name: "芽生术",
    nameEn: "Sprouting Art",
    type: "spell",
    sources: ["verdant"],
    cost: 1,
    rarity: "common",
    text: "治疗一名友方幻兽 20 点。若其为森源，查看牌库顶 1 张。",
    artHue: 110,
    artKind: "spell",
  },
  stardust: {
    id: "stardust",
    name: "星屑占卜",
    nameEn: "Stardust Augury",
    type: "spell",
    sources: ["astral"],
    cost: 1,
    rarity: "common",
    text: "查看牌库顶 3 张，任意重排。",
    artHue: 230,
    artKind: "spell",
  },
  borrowed_dawn: {
    id: "borrowed_dawn",
    name: "借来的晨光",
    nameEn: "Borrowed Dawn",
    type: "spell",
    sources: ["astral", "verdant"],
    cost: 2,
    rarity: "rare",
    text: "选择 1 只己方幻兽，治疗 30 点。若你的主契为星源，再查看牌库顶 2 张牌。",
    artHue: 45,
    artKind: "spell",
  },
  chart_align: {
    id: "chart_align",
    name: "星图校准",
    nameEn: "Chart Alignment",
    type: "spell",
    sources: ["astral"],
    cost: 2,
    rarity: "rare",
    text: "查看牌库顶 4 张。将其中 1 张幻兽或遗物加入手牌，其余按原相对顺序放回牌顶。计为一次检索。",
    artHue: 215,
    artKind: "spell",
  },
  old_scope: {
    id: "old_scope",
    name: "旧天文镜",
    nameEn: "Old Observatory Glass",
    type: "relic",
    sources: ["astral"],
    cost: 2,
    rarity: "relic",
    text: "每回合第一次查看己方牌顶时，额外多看 1 张。多份不叠加。",
    artHue: 210,
    artKind: "relic",
  },
  moss_basin: {
    id: "moss_basin",
    name: "苔石盆",
    nameEn: "Moss-Stone Basin",
    type: "relic",
    sources: ["verdant"],
    cost: 1,
    rarity: "relic",
    text: "夜幕：若主契为森源，治疗其 10 点。",
    artHue: 130,
    artKind: "relic",
  },
  eve: {
    id: "eve",
    name: "守林人·伊芙",
    nameEn: "Eve, Grove Warden",
    type: "traveler",
    sources: ["verdant"],
    cost: 2,
    rarity: "rare",
    text: "从牌库列出所有森源幻兽，选择 1 张加入手牌，然后洗牌。",
    artHue: 100,
    artKind: "traveler",
  },
  norn: {
    id: "norn",
    name: "观测师·诺恩",
    nameEn: "Norn, Observer",
    type: "traveler",
    sources: ["astral"],
    cost: 2,
    rarity: "arcane",
    text: "查看牌库顶 5 张。将其中 1 张星源牌加入手牌，其余以任意顺序置于牌底。",
    artHue: 240,
    artKind: "traveler",
  },
  mist_night: {
    id: "mist_night",
    name: "雾林深夜",
    nameEn: "Deep Night of the Mistwood",
    type: "environment",
    sources: ["verdant"],
    cost: 2,
    rarity: "rare",
    text: "每回合每只森源幻兽第一次受到伤害时，该伤害减少 10 点（最低 0）。",
    artHue: 160,
    artKind: "env",
  },
  ash_lizard: {
    id: "ash_lizard",
    name: "烬尾蜥",
    nameEn: "Cinder-Tail Lizard",
    type: "eidolon",
    sources: ["ember"],
    cost: 1,
    rarity: "common",
    hp: 60,
    skill: {
      name: "烬咬",
      cost: 1,
      text: "造成 30 点伤害，然后自身受到 10 点伤害。",
      strike: { damage: 30 },
      follow: [{ kind: "selfDamage", amount: 10 }],
    },
    text: "自伤会推进烬源共鸣。",
    artHue: 18,
    artKind: "ember",
  },
  ash_crown: {
    id: "ash_crown",
    name: "灰冠火蜥",
    nameEn: "Ash-Crown Salamander",
    type: "eidolon",
    sources: ["ember"],
    cost: 1,
    rarity: "rare",
    hp: 90,
    resonanceFrom: "ash_lizard",
    resonanceCost: 1,
    resonanceText: "本局己方烬源幻兽累计受到至少 20 点自伤。",
    skill: {
      name: "灰焰",
      cost: 2,
      text: "造成 40 点伤害。若本回合受到过友方效果伤害，改为 50 点。",
      strike: { damage: 40, altWhen: "friendlyEffectDamage", altDamage: 50 },
    },
    text: "烬尾蜥的共鸣形态。",
    artHue: 12,
    artKind: "ember",
  },
  ash_crow: {
    id: "ash_crow",
    name: "灰羽鸦",
    nameEn: "Ash-Feather Crow",
    type: "eidolon",
    sources: ["ember"],
    cost: 1,
    rarity: "rare",
    hp: 60,
    skill: {
      name: "焦羽",
      cost: 1,
      text: "造成 20 点伤害。可选：弃 1 张牌，抽 1 张牌。",
      strike: { damage: 20 },
      follow: [{ kind: "optionalDiscard" }],
    },
    text: "以自身羽毛为代价。",
    artHue: 8,
    artKind: "ember",
  },
  ember_emperor: {
    id: "ember_emperor",
    name: "余烬鸦皇",
    nameEn: "Cinder Emperor",
    type: "eidolon",
    sources: ["ember"],
    cost: 2,
    rarity: "arcane",
    hp: 100,
    resonanceFrom: "ash_crow",
    resonanceCost: 2,
    resonanceText: "本局你的卡累计进入弃牌区至少 3 次。",
    skill: {
      name: "葬羽",
      cost: 2,
      text: "造成 40 点伤害。可选：将弃牌中 1 张烬源牌洗回牌库，若如此则再造成 10 点。",
      strike: { damage: 40 },
      follow: [{ kind: "optionalDiscardEmber" }],
    },
    text: "灰羽鸦的共鸣形态。",
    artHue: 5,
    artKind: "ember",
  },
  furnace_mole: {
    id: "furnace_mole",
    name: "炉心鼹",
    nameEn: "Furnace-Heart Mole",
    type: "eidolon",
    sources: ["ember"],
    cost: 2,
    rarity: "common",
    hp: 80,
    skill: {
      name: "炉击",
      cost: 2,
      text: "造成 20 点伤害。可选：自身受到 10 点，获得 1 点临时灵息。",
      strike: { damage: 20 },
      follow: [{ kind: "optionalSelfDmg" }],
    },
    text: "把热炼成气息。",
    artHue: 25,
    artKind: "ember",
  },
  tide_jelly: {
    id: "tide_jelly",
    name: "潮铃水母",
    nameEn: "Tide-Bell Jelly",
    type: "eidolon",
    sources: ["tide"],
    cost: 1,
    rarity: "common",
    hp: 60,
    skill: {
      name: "铃潮",
      cost: 1,
      text: "造成 10 点伤害，然后你可以免费换位。",
      strike: { damage: 10 },
      follow: [{ kind: "optionalFreeSwitch" }],
    },
    text: "一枚淡水的铃。",
    artHue: 190,
    artKind: "tide",
  },
  silver_umbrella: {
    id: "silver_umbrella",
    name: "银潮伞母",
    nameEn: "Silver-Tide Umbrella",
    type: "eidolon",
    sources: ["tide"],
    cost: 1,
    rarity: "rare",
    hp: 100,
    resonanceFrom: "tide_jelly",
    resonanceCost: 1,
    resonanceText: "本场至少完成 3 次换位。",
    skill: {
      name: "静潮",
      cost: 2,
      text: "造成 20 点伤害。对方主契下一次攻击伤害减少 20 点（最低 0）。",
      strike: { damage: 20 },
      follow: [{ kind: "nextAttackReduction", amount: 20 }],
    },
    text: "潮铃水母的共鸣形态。",
    artHue: 195,
    artKind: "tide",
  },
  moon_cat: {
    id: "moon_cat",
    name: "月潮猫",
    nameEn: "Moon-Tide Cat",
    type: "eidolon",
    sources: ["tide"],
    cost: 2,
    rarity: "rare",
    hp: 70,
    skill: {
      name: "月痕",
      cost: 1,
      text: "造成 20 点伤害。若本回合进入过主契位，改为 30 点。",
      strike: { damage: 20, altWhen: "enteredActiveThisTurn", altDamage: 30 },
    },
    text: "落地时已在跃中。",
    artHue: 205,
    artKind: "tide",
  },
  mirror_cat: {
    id: "mirror_cat",
    name: "镜月灵猫",
    nameEn: "Mirror-Moon Spirit Cat",
    type: "eidolon",
    sources: ["tide"],
    cost: 1,
    rarity: "arcane",
    hp: 100,
    resonanceFrom: "moon_cat",
    resonanceCost: 1,
    resonanceText: "此月潮猫本场至少两次从伴契进入主契位。",
    skill: {
      name: "镜影",
      cost: 2,
      text: "造成 30 点伤害。若本回合进入过主契位，抽 1 张牌。",
      strike: { damage: 30 },
      follow: [{ kind: "drawIfEnteredActive" }],
    },
    text: "月潮猫的共鸣形态。",
    artHue: 215,
    artKind: "tide",
  },
  ash_borrow: {
    id: "ash_borrow",
    name: "灰烬借火",
    nameEn: "Borrowed Cinder",
    type: "spell",
    sources: ["ember"],
    cost: 0,
    rarity: "common",
    text: "每回合限一次。对一名友方烬源幻兽造成 10 点伤害，获得 1 点临时灵息。",
    artHue: 16,
    artKind: "spell",
  },
  tide_return: {
    id: "tide_return",
    name: "潮汐折返",
    nameEn: "Tidefold Return",
    type: "spell",
    sources: ["tide"],
    cost: 1,
    rarity: "common",
    text: "免费换位。若新主契为潮源，治疗其 10 点。",
    artHue: 188,
    artKind: "spell",
  },
  scar_burst: {
    id: "scar_burst",
    name: "烬痕爆裂",
    nameEn: "Scar Burst",
    type: "spell",
    sources: ["ember"],
    cost: 2,
    rarity: "rare",
    text: "需要本回合有友方幻兽受到过自伤。对对方主契造成 20 点直接伤害。",
    artHue: 10,
    artKind: "spell",
  },
  warm_reclaim: {
    id: "warm_reclaim",
    name: "余温回收",
    nameEn: "Residual Warmth",
    type: "spell",
    sources: ["ember"],
    cost: 2,
    rarity: "rare",
    text: "将弃牌中 1 张烬源幻兽收回手牌。然后你的主契受到 10 点伤害。",
    artHue: 22,
    artKind: "spell",
  },
  ash_scheme: {
    id: "ash_scheme",
    name: "灰羽谋算",
    nameEn: "Ash-Feather Scheme",
    type: "spell",
    sources: ["ember"],
    cost: 1,
    rarity: "common",
    text: "弃 1 张牌，抽 2 张牌。",
    artHue: 14,
    artKind: "spell",
  },
  ash_furnace: {
    id: "ash_furnace",
    name: "灰烬炉",
    nameEn: "Ash Furnace",
    type: "relic",
    sources: ["ember"],
    cost: 2,
    rarity: "relic",
    text: "每回合第一次友方自伤时获得 1 点临时灵息。多份不叠加。",
    artHue: 20,
    artKind: "relic",
  },
  moon_mirror: {
    id: "moon_mirror",
    name: "月潮镜",
    nameEn: "Moon-Tide Mirror",
    type: "relic",
    sources: ["tide"],
    cost: 2,
    rarity: "relic",
    text: "每回合你的第一次换位后，治疗新主契 10 点。",
    artHue: 200,
    artKind: "relic",
  },
  alo: {
    id: "alo",
    name: "烬匠·阿洛",
    nameEn: "Alo, Cinderwright",
    type: "traveler",
    sources: ["ember"],
    cost: 2,
    rarity: "rare",
    text: "对一名友方幻兽造成 10 点伤害。从牌库检索 1 张烬源牌加入手牌，然后洗牌。",
    artHue: 18,
    artKind: "traveler",
  },
  mira: {
    id: "mira",
    name: "渡潮者·弥拉",
    nameEn: "Mira, Tide-Crosser",
    type: "traveler",
    sources: ["tide"],
    cost: 2,
    rarity: "arcane",
    text: "免费换位。若新主契为潮源，抽 1 张牌。",
    artHue: 192,
    artKind: "traveler",
  },
  ash_rain: {
    id: "ash_rain",
    name: "灰雨",
    nameEn: "Ash Rain",
    type: "environment",
    sources: ["ember"],
    cost: 2,
    rarity: "rare",
    text: "所有治疗减少 10 点（最低 0）。",
    artHue: 0,
    artKind: "env",
  },
  high_tide: {
    id: "high_tide",
    name: "月潮涨时",
    nameEn: "When the Moon-Tide Rises",
    type: "environment",
    sources: ["tide"],
    cost: 2,
    rarity: "rare",
    text: "每回合第一次普通换位费用为 0。潮源进入主契位时，其本回合下次攻击 +10 伤害。",
    artHue: 198,
    artKind: "env",
  },
};

export const INITIAL_ARRIVAL_HELP =
  "初临：本回合从手牌部署的幻兽不能发动攻击型战技。开局绑定的主契与伴契不视为初临。";

export function computeStrikeDamage(
  skill: NonNullable<CardDef["skill"]>,
  e: { enteredActiveThisTurn: boolean; friendlyEffectDamageThisTurn: boolean }
): number {
  const st = skill.strike;
  if (!st) return 0;
  if (st.altWhen === "enteredActiveThisTurn" && e.enteredActiveThisTurn) return st.altDamage ?? st.damage;
  if (st.altWhen === "friendlyEffectDamage" && e.friendlyEffectDamageThisTurn) return st.altDamage ?? st.damage;
  return st.damage;
}

export function def(id: string): CardDef {
  const d = CARDS[id];
  if (!d) throw new Error(`Unknown card ${id}`);
  return d;
}

export const BASIC_STARTERS = new Set([
  "moss_sleep",
  "vine_weasel",
  "microstar",
  "star_owl",
  "star_fox",
  "pale_wood",
  "ash_lizard",
  "ash_crow",
  "furnace_mole",
  "tide_jelly",
  "moon_cat",
]);

export function isBasicEidolon(id: string): boolean {
  const d = CARDS[id];
  return d?.type === "eidolon" && !d.resonanceFrom && BASIC_STARTERS.has(id);
}

export function starterBindError(defId: string): string | null {
  const d = CARDS[defId];
  if (!d) return "未知卡牌。";
  if (d.resonanceFrom) {
    const base = CARDS[d.resonanceFrom]?.name ?? "对应基础形态";
    return `${d.name}是共鸣形态，无法直接部署。请先部署${base}，并在对局中满足共鸣条件。`;
  }
  if (d.type !== "eidolon") return `${d.name}无法作为主契。`;
  if (!isBasicEidolon(defId)) return `${d.name}无法作为开局主契。`;
  return null;
}

export const RARITY_LABEL: Record<string, string> = {
  common: "◇ 常契",
  rare: "◆ 珍契",
  arcane: "✦ 秘契",
  relic: "✧ 遗契",
  mythic: "✦✦ 神契",
};

export const SOURCE_LABEL: Record<string, string> = {
  verdant: "森",
  tide: "潮",
  ember: "烬",
  astral: "星",
};

export const TYPE_LABEL: Record<string, string> = {
  eidolon: "幻兽",
  spell: "灵术",
  relic: "遗物",
  traveler: "旅者",
  environment: "环境",
};
